### ISSUE TITLE
An error occured when I start the example

### ISSUE THREAD

**Issue by zzy199311** [riebl/artery#10]
I try to install artery and succeed,then I try to input "cmake --build build --target run example" into IDE, and error appeared.
It located in inet/src/inet/visualizer/networknode/NetworkNodeOsgVisualization.cc。
Error as follow:
inet/visualizer/networknode/NetworkNodeOsgVisualization.cc: In constructor ‘inet::visualizer::NetworkNodeOsgVisualization::NetworkNodeOsgVisualization(omnetpp::cModule*, bool)’:
inet/visualizer/networknode/NetworkNodeOsgVisualization.cc:131:39: error: expected type-specifier
     auto objectNode = new cObjectOsgNode(networkNode);

I try to search and locate the class/function cObjectOsgNode,but failed.
so I wonder how to fix it?
Anyway, thank u.

**Comment by riebl** [comment]
As you can guess from the file name, this is actually an INET issue. It may be enough to add `#include <omnetpp/osgutil.h>` to NetworkNodeOsgVisualization.cc, however, I haven't verified this because I am not using the OpenSceneGraph feature at all. You might also try to deactivate INET's visualization feature completely: `cd extern/inet && ./inet_featuretool disable visualization`
