### ISSUE TITLE
Packet collision

### ISSUE THREAD

**Issue by danieladriano** [riebl/artery#120]
Hi, @riebl

In Veins to collect packet collision statistics, it's possible to use the `*.**.nic.phy80211p.collectCollisionStatistics = true` flag in `omnetpp.ini`. This enables collision statistics in `Decider80211p` on all nodes in your scenario which then record `ncollisions`.

How can I get the packet collision info in Artery? I need to get the number of collisions.

Regards,
Daniel

**Comment by riebl** [comment]
From your question, I conclude that you do not use the Veins radio modules in your Artery simulation but INET.
INET's MAC has a `statistics` submodule, however, this one has been entirely disabled by INET developers. I don't know the reason, maybe this feature has been just forgotten.

Counting collisions can become somewhat tricky and I don't remember when Veins counts a packet as a collision. Due to the capture effect, at least one of two or more concurrent receptions may be decodable. Do you want to count this as a collision or only if nothing is successfully received at all?

You may employ some signals emitted by INET to count collisions: `RadioMedium` emits a signal for each started reception. Also, `Radio` emits a signal whenever its reception state changes. Maybe increment collision counter whenever a "start reception" signal is not accompanied by a reception state change, i.e. the respective radio is already receiving something else?
Maybe INET user group can give you a good hint as well.
