### ISSUE TITLE
Buildings as obstacles for INET testing

### ISSUE THREAD

**Issue by libertt1** [riebl/artery#130]
Hi @riebl,

I would like to add static obstacles to my scenario to test INET models. I read that TraCI would update the polys once connected. I tried to do so by adding my buildings in an additional file as in the mti-its example. Are these objects supposed to appear on omnet GUI or are they juste considered by the Global Environment? Do I need to create them via OMNET? 

Thanks

**Comment by riebl** [comment]
The `GlobalEnvironment` module fetches TraCI polygons and adds them to its obstacle database. This module will also draw its obstacles if you enable this feature by its `drawObstacles` parameter on its own module canvas, i.e. you need to open the window of this canvas explicitly in the GUI to see it. It should similar to the screenshots on http://artery.v2x-research.eu/features/envmod/
It is normal that you don't see any polygons on the main canvas, though.

You may want to use SUMO's netedit tool to modify SUMO maps and also its polygons instead of manually editing XML files.

**Comment by libertt1** [comment]
I created the polygons using netedit and added to the .sumocfg. I tried adding the drawObstacles as default true to make sure. What name should have the canvas on omnetpp? I only have the World.canvas, should World change?

**Comment by riebl** [comment]
The canvas is at `World.environmentModel.canvas`. Just click on it in the module tree of the OMNeT++/Qtenv window.
