### ISSUE TITLE
Docker container fails on start - Different package versions in build and run stage

### ISSUE THREAD

**Issue by marecabo** [riebl/artery#152]
After building the docker image and starting the container with

```bash
docker run -d \
  --name artery \
  -v /home/ubuntu/artery/scenarios/artery:/scenario \
  -v /home/ubuntu/artery/results:/results \
  artery \
  -c inet
```
the container exits with the following:

```log
<!> Error: Cannot load library '/artery/lib/libartery_core.so': libcrypto++.so.8: cannot open shared object file: No such file or directory
```

**Comment by marecabo** [comment]
This issue stems from different versions of the packages in the artery-build and run stage.

The affected packages in the run stage are:
- libboost-date-time1.71.0
- libboost-system1.71.0
- libcrypto++6
- libpython3.8

Setting them to the current versions from the *-dev packages (e.g. [libboost-system-dev](https://packages.debian.org/bullseye/libboost-system-dev)) solves this issue (and the other ones of the same kind).
- libboost-date-time1.74.0
- libboost-system1.74.0
- libcrypto++8
- libpython3.9

**Comment by riebl** [comment]
Thanks @marecabo for your proposal. I have revised the Dockerfile and pinned Boost, Crypto++ and Python libraries.
I have no problem running Artery simulations with Docker anymore. Please note that *scenarios/artery* does not work out-of-the-box with Docker because it references *erlangen.sumo.cfg* from a directory, which is not present in the Docker container. However, it runs fine with copies of the Erlangen SUMO scenario copied into */scenario* and accordingly adjusted *omnetpp.ini*.

**Comment by marecabo** [comment]
> However, it runs fine with copies of the Erlangen SUMO scenario copied into /scenario and accordingly adjusted omnetpp.ini.

You're right, I quietly did that, but it's definitely better to mention it here for the future.

The container now runs well for me with the current Dockerfile. Thanks for the quick fixes! 👍
