### ISSUE TITLE
Adaptive and reactive DCC

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#166]
Hi @riebl, 

I'm trying to simulate 2 scenarios where in the first one I use **TRC reactive DCC**, and in the second I use the **LIMERIC** algorithm. 
If I understood an earlier answer of yours, for TRC, I should set _TransmitRateControl_ to _StateMachine_. However; for the adaptive approach, I can't find another option to put except Bursty, which; as far as I understand,  is not LIMERIC. What can I do ?

My second question is about the dual alpha algorithm. If I want to use the **Dual alpha** for  **LIMERIC**, I think I should set _enableDualAlpha_ to true in _LimericDccEntity.ned_. What about **Dual alpha of ETSI adaptive approach** (as in 10.1109/LCOMM.2019.2906178)?

Thanks in advance, and sorry for the trouble.

**Comment by kenog** [comment]
Hi,

in order to use the reactive approach, you need to set `typename` to `FsmDccEntity`. For Limeric, set it to `LimericDccEntity`. So in your omnetpp.ini you would have something like `**.vanetza[*].dcc.typename = LimericDccEntity`.
I am afraid I don't understand the second part of your question though. The ETSI adaptive DCC approach is based on Limeric. So if you use `LimericDccEntity` (with or without dual alpha), that actually _is_ the adaptive approach.

Best regards
Keno
