### ISSUE TITLE
call Python from Artery

### ISSUE THREAD

**Issue by SamirRachedi** [riebl/artery#171]
Hi @riebl,

as part of a study project, I need to call a method implemented in Python3.6 (in a file called project.py) from a service I created (personalized service). I'm using the tutorial on this page: 

_https://medium.datadriveninvestor.com/how-to-quickly-embed-python-in-your-c-application-23c19694813_

I need to give this method an input from my service, then I retrieve the method's output to use it later.

When I added **#include <Python.h>** to my code it can't find it. then I used #include <python3.6/Python.h> it gave me this error

_Error: Cannot load library '..../test/libartery_test.so': ..../scenarios/test/libartery_test.so: undefined symbol: PyUnicode_FromString_

I tried to use **#include <boost/python.hpp>** but it gave me this error: 

Cannot load library '.../artery/build/scenarios/test/libartery_test.so': .../artery/build/scenarios/test/libartery_test.so: undefined symbol: _Py_NoneStruct

First, Is it even possible to call a python method from Artery?  If yes is there a way to overcome these errors?

Thanks a lot.

**Comment by riebl** [comment]
Yes, you can call Python code from OMNeT++/Artery. We are using Python for our storyboard feature. Instead of Boost.Python I recommend pybind11, which is shipped along with Artery in *extern/pybind11*. You can consult *src/artery/storyboard/CMakeLists.txt* how to link your code with pybind11. pybind11 has also quite good documentation on how to make Python functions available in C++.

**Comment by SamirRachedi** [comment]
Working just fine. Thanks a lot.
