### ISSUE TITLE
Very Slow Simulation Speed

### ISSUE THREAD

**Issue by kinjaLICIT** [riebl/artery#173]
Hi I am trying to use Artery to simulate different C-ITS use cases. I am currently running it in the virtual machine using Vagrant. When I try to run my code or even the examples using the OMNETPP IDE and when more vehicles are loaded into the network, the simulation speed becomes very very slow (between 0.33 to 0.05 Simsec/sec) even when I don't use the GUI of sumo. Also while running the simulation, it is taking up a lot of disk space (about 2.5 GB for about 600 seconds of simulation with 100 vehicles), which is being restored once the run is complete. I am very new to Artery and I would really appreciate any help in speeding up the simulation or reducing the hard disk space requirements during the simulation.

**Comment by riebl** [comment]
For the fastest simulation execution speeds, I recommend running with Cmdenv instead of the Qtenv user interface in the first step. Furthermore, building everything in release mode (set CMAKE_BUILD_TYPE to "Release") speeds up execution also a lot.
The penalty of running OMNeT++ in a virtual machine hurts as well with many vehicles, so you may want to run OMNeT++ without a virtualisation layer between.

I cannot say what is consuming the disk space only while you are running a simulation. Result and log files do persist a run, they may only get overwritten when you start the same configuration again.

**Comment by kinjaLICIT** [comment]
Thanks for the prompt response. I have already set the Cmdenv express mode. The virtualisation layer seems to be a problem - is a stable Windows/MacOS version (like for Veins) being planned? Regarding the disk space, I have checked the result and log files and they don't consume so much space.

**Comment by riebl** [comment]
No, I have no plans to support Windows or MacOS due to my limited time. This would need to be contributed by the community.
