### ISSUE TITLE
Sending personnalized DenService at a specific time 

### ISSUE THREAD

**Issue by 1234MaDa** [riebl/artery#246]
Hi, i need an urgent help within this please !!

I am working on a vehicular environment with artery , actually in my situation i have a vehicle that will be blocked on a railway at a level-crossing, an RSU installed just near the level-crossing has to receive a DENM from the blocked vehicle at that particular second/time and broadcast the DENM to other vehicles. 
 I am trying to understand the DenService but i don't know how to add this to the the given DenService to make it work as i want it to ! 

Any suggestions please ? i mean ... how to make the blocked vehicle send the DENM to the RSU at a specific time by using the Denservice to tell the RSU that it is blocked on the railway ? and how the RSU broadcasts the alert just after receiving it ? 

Is that possible on artery (The DENM in this case is sent just 2 times in my simulation : 
- From the blocked vehicle to the RSU 
- And from the RSU to neighbour vehicles ). 

Thanks in advance !

**Comment by riebl** [comment]
Hi @1234MaDa,

please note that DEN messages are sent as GeoBroadcast packets at network layer, i.e. these messages are never explicitly sent from one station to another. Does the RSU have any special properties in your scenario, e.g. higher transmission power or an elevated antenna position? Otherwise, I see no benefit in having the nearby RSU send such a "blocked on railway" message instead of the vehicle itself.

**Comment by 1234MaDa** [comment]
Hi @riebl ! Thank you for answering me ! 

Actually i am using the RSU as an Edge server ( supposing that an Edge server is installed on the RSU) because a train that is still far from the level-crossing has to receive the alert 5 kilometers before arriving at the Level-crossing, therefore i added an Edge server installed on the RSU that will send the alert received from the blocked vehicle to an eNodeB and the latter will send the alert to the train so that it brakes before arriving to the level-crossing, what i am really searching for is sending the DENM message from the RSU to the Edge server and from the edge server to eNodeB, i thought about broadcasting the message from the RSU but it might not be the best solution as you said because vehicles have already received the alert from the blocked car , is there a way to encapsulate the DENM message and send it just to the Edge server from the RSU without broadcasting it ? 

Thank you in advance !

**Comment by riebl** [comment]
The GeoNetworking standard specifies so-called GeoUnicasts which would allow you to send a message to a particular station identified by its GeoNetworking address. This requires that you know the destination's address beforehand, though. GeoUnicasts are also not implemented in Vanetza (and thus Artery) because no relevant use case is known to me.

Assuming that your RSU has received the relevant information from a vehicle, you can copy the received DENM into an IP packet and send it to any IP destination via the cellular network. The principles are the same as a real-world implementation would forward such information.
