### ISSUE TITLE
Import and execute artery on OMNET

### ISSUE THREAD

**Issue by aintzel2** [riebl/artery#253]
Hi.

I'm having problems implementing Vanetza libraries in my project and I can't find a way to import any project to the OMNET++ IDE that uses Vanetza. The first example that you offer the one that is executed with "make run_example" in the /artery-build directory does use Vanetza, the question is that I can't import the source project (/artery) to the OMNET++ IDE. When I import  /artery directory I get errors.
 
**So I wanted to ask you if it is possible to import the /artery project to the OMNET++ IDE to be able to run and it there or is it only possible to run it using the "make" command.**

Regards

**Comment by aintzel2** [comment]
I tried using vsCode IDE instead of OMNET++ and it works perfectly. 

Try this video on youtube: "OMNeT++ 2021: Towards a modern CMAKE workflow (Heinz-Peter Liechtenecker and Raphael Riebl)"

**Comment by riebl** [comment]
It is already several years ago that I have used the OMNeT++ IDE at all. Since it is based on Eclipse CDT, you should be able to open the project generated by `cmake -G "Eclipse CDT4 - Unix Makefiles"` with the OMNeT++ IDE. Though it is likely feasible to use the OMNeT++ IDE with Artery, I do not recommend it and I cannot help with any problems arising from this combination.
That said, VSCode is a good choice!
