### ISSUE TITLE
Problems with vagrant on Windows

### ISSUE THREAD

**Issue by Mondraupe** [riebl/artery#267]
Hi,
I would like to use Artery on a VM on windows. I can run "vagrant up" from Artery's root directory, but
the login credentials that are written on the website don't work (username: "vagrant", pw: "vagrant").
I can login with username: "root" and pw: "vagrant", but with this login I haven't any directorys.
Could you tell me what i did wrong?

**Comment by riebl** [comment]
Hi @Mondraupe,

I don't think that you have done anything wrong. My guess is that the default setup of Vagrant (or at least the used Debian box) has changed, in particular, the "vagrant" user login has been disabled.
As a workaround, just can explicitly set the password for "vagrant" when logged in as "root": `passwd vagrant`
I suppose the problem is only with the lock screen, right?

**Comment by riebl** [comment]
I have updated the Vagrant setup with 9764979c. You may want to give it a try.

**Comment by Mondraupe** [comment]
Thanks for the reply. I tested the new Vagrant setup and set the password for vagrant with passwd vagrant.
Now i can login as vagrant, but there are no input files. So i can't go to /artery-build/ and start artery as described on the website.

**Comment by riebl** [comment]
Sounds like something went wrong during the initial provisioning of the machine by Vagrant. You may either destroy the VM and start from scratch again with a fresh machine or explicitly run the provisioning steps again with `vagrant up --provision`.
