### ISSUE TITLE
Run both envmod and simulte

### ISSUE THREAD

**Issue by JohnnyMinho** [riebl/artery#344]
Hello! 
I'm trying to implement some RSUs to receive data from a server in a simulation that is based on bikes using LTE to send their location to a server and then make that information available trough a RSU connected to the server.
In my attempts to do this I tried to base myself on the 5x5 rsu grid scenario and the simulte scenario.
However, I came to the conclusion (which might be wrong) that I have to include both the artery.envmod.World and artery.lte.World, however I do not know how to do this without causing problems.
I have already tried trough the Config and extend but that didn't work.

**Comment by JohnnyMinho** [comment]
I ended up implementing the inet RSUs, however I'm still curious if it possible to use both envmod and simulte.

**Comment by riebl** [comment]
You are right, the combination of EnvMod and SimuLTE is not supported out of the box. However, you can adapt `artery.envmod.World` to extend `artery.lte.World` instead of `artery.inet.World`. We could add this as `artery.envmod.LteWorld`, for example.
Unfortunately, I don't know a better way yet to mix-in features in their various combinations. If someone has a good idea I would love to hear it :-)

**Comment by JohnnyMinho** [comment]
Seems like a good way to do it.
If it isn't a problem I would also like to ask if I can make a service based on LTE or if it is easier to add my own application to the simuLTE module (I'm asking here since the simuLTE repo isn't maintained anymore).
I still have to check the blackice-LTE scenario to verify if the LTE service making aspect is possible.

Best regards.
