### ISSUE TITLE
CAM timestamp resolution

### ISSUE THREAD

**Issue by masa1228masa** [riebl/artery#57]
Hello,

I want to measure the delay of CAM dissemination.
So I want to put cam.generationDeltaTime in 'ms' resolution.
But it seems that "mLastUpdate" in "VehicleDataProvider::update" has only '10^-1s' resolution (I did cout << mLastUpdate << endl;).

I tried to fix this, but I couldn't.
Is this a bug? Or my configuration's fault?

Best regards,
Masahiro

**Comment by riebl** [comment]
The time stamp of `VehicleDataProvider` is updated whenever vehicle data from SUMO is processed, i.e. at SUMO steps which are by default 100 ms in Artery.
`CaService` uses the update time stamp from `VehicleDataProvider` to fill `generationDeltaTime`, see CaService.cc:132. You can change `mTimer->getTimeFor(mVehicleDataProvider->updated())` to `mTimer->getCurrentTime()` to include the current simulation time instead.

**Comment by masa1228masa** [comment]
Does the time stamp of `VehicleDataProvider` match the time stamp of CAM generation(`mTimer->getCurrentTime()`)?
According to 6.1.5.2 in https://www.etsi.org/deliver/etsi_en/302600_302699/30263702/01.03.02_60/en_30263702v010302p.pdf,
in the case of vehicle ITS-S, CAM should have the time when `VehicleData` was determined, not the time when CAM was generated.
And from your information about `VehicleDataProvider` update interval, if I set `fixedRate` in `CaService` to true and `updateInterval` in `Middleware` to 0.1s, 
I think there should be the time gap from 0ms to 50ms between them.
So is it correct to use `mTimer->getCurrentTime()` instead of using `mTimer->getTimeFor(mVehicleDataProvider->updated())` ?

**Comment by riebl** [comment]
No, `VehicleDataProvider` reports the time stamp of the latest vehicle data update. Because of the mentioned CAM specification, `CaService` uses the time stamp from `VehicleDataProvider` to fill the CAM `generationDeltaTime`.
Time points of CAM generation and vehicle data updates are not linked, even when a fixed generation rate is used: Vehicle data is updated for all vehicles at the same time point, but services are triggered with some random delay among vehicles so they do not synchronise artificially.
While using `mTimer->getCurrentTime()` violates the CAM requirements w.r.t. `generationDeltaTime`, I guess nobody will punish you when you are doing this in a simulation ;-)

**Comment by masa1228masa** [comment]
Okey! Thank you very much!
