### ISSUE TITLE
Generate GeoBroadcasts and forwarding questions

### ISSUE THREAD

**Issue by fehlfarbe** [riebl/artery#79]
Hi,

I want to compare different forwarding algorithms for ETSI GeoNetworking GeoBroadcasts. Artery seems a good tool for this but I have some starting issues because I don't really know how to start my project.

At the moment I'm working with the artery example (Erlangen) but later I want to generate different scenarios in SUMO with random placed cars and routes (every car is in range of the predecessor). The first generated car should send a message to the area where the last generated car is located so there is always a receiver in the destination area.

How can I do this with artery?

My idea is to create a new ItsG5Service "CustomService" that sends a message with GBC to a defined area:
    - how can I access the current node/car id in the CustomService class and also get the position of the last car in the scenario?
    - how can I distinguish between the forwareded and received (= node is in destination area) messages in the CustomService
    - can I trigger the service with the storyboard module? Maybe that's a better way to get the destination area? Is there some more documentation for this module despite the example?

To implement my own router for GBC the simplest way would be to inherit from `artery.networking.Router` and replace the GBC part in `Router::request`?

Thanks in advance!

**Comment by riebl** [comment]
Dear @fehlfarbe,

> - how can I access the current node/car id in the CustomService class and also get the position of the last car in the scenario?

Every service attached to a vehicle (i.e. running on top of `VehicleMiddleware`) can access its `VehicleDataProvider` and `VehicleController` via Facilities. See https://github.com/riebl/artery/blob/master/src/artery/application/CaService.cc#L60 for an example.
Artery (and also ETSI ITS) has no notion about "last car" so you will need to determine this on your own. It might be helpful to think about how this could be determined in a real deployment.

> - how can I distinguish between the forwareded and received (= node is in destination area) messages in the CustomService

Services only receive GeoBroadcast packets if they are within the addressed destination area. Line-forwarding is handled by the GeoNet router transparently just as specified by ETSI. Consequently, if a vehicle forwards a packet without being inside the addressed area, this packet is not passed up to its application layer.

> - can I trigger the service with the storyboard module? Maybe that's a better way to get the destination area? Is there some more documentation for this module despite the example?

Well, beside the included examples, there are the original paper "Dynamic scenario control for VANET simulations" (DOI: 10.1109/MTITS.2017.8005599) and since recently a book chapter in "Recent Advances in Network Simulation" (DOI: 10.1007/978-3-030-12842-5).
However, I don't think that the Storyboard helps you with moving destination areas.

> To implement my own router for GBC the simplest way would be to inherit from artery.networking.Router and replace the GBC part in Router::request?

No, artery.networking.Router is just the integration of `vanetza::geonet::Router`. I suggest to modify `vanetza::geonet::Router` instead.

**Comment by fehlfarbe** [comment]
Thanks that helps a lot!
Sending messages with SHB is working but same code with GBC doesn't work. The cars don't receive the message

That's my code in trigger():
```
btp::DataRequestB req;
req.destination_port = host_cast<DummyService::port_type>(getPortNumber());
req.gn.transport_type = geonet::TransportType::GBC;
req.gn.traffic_class.tc_id(static_cast<unsigned>(dcc::Profile::DP3));
req.gn.communication_profile = geonet::CommunicationProfile::ITS_G5;
using vanetza::units::si::meters;
static const auto microdegree = vanetza::units::si::micro * vanetza::units::degree;

vanetza::geonet::Area area;
area.shape = vanetza::geonet::Circle();
boost::get<vanetza::geonet::Circle>(area.shape).r = 30.0 * meters;
area.position.latitude = vanetza::units::GeoAngle{49.573927 * 0.1 * microdegree};
area.position.longitude = vanetza::units::GeoAngle{11.031362 * 0.1 * microdegree};
area.angle = vanetza::units::Angle{0.0 * vanetza::units::degrees};
req.gn.destination = area;

cPacket *packet = new cPacket("DUMMY Service Packet");
packet->setByteLength(42);
request(req, packet);
```

The area position is the "spawn point" in erlangen example. Maybe the problem is related to #58? At the moment I'm working on the inet4 branch because master doesn't compile on Ubuntu 18.04 (see #63) maybe it's already fixed in master?

**Comment by riebl** [comment]
> vanetza::units::GeoAngle{49.573927 * 0.1 * microdegree};

This number (and same for longitude) is not microdegree but 1/10 degree, try `vanetza::units::GeoAngle { 49.573927 * degree }` instead.

**Comment by riebl** [comment]
If a sender is not within the destination area then non-area forwarding applies.
You can switch from greedy forwarding (the default) to CBF by setting `itsGnNonAreaForwardingAlgorithm` accordingly. Greedy forwarding as specified is known to have a problem in communication scenarios as yours.

**Comment by fehlfarbe** [comment]
Thanks again! I didn't read the ETSI specs carefully enough and misinterpreted the `itsGnNonAreaForwardingAlgorithm` field. Now everything is working as expected :)
